
!Copyright (c) 2009-2010, Tom Schoonjans
!All rights reserved.

!Redistribution and use in source and binary forms, with or without
!modification, are permitted provided that the following conditions are met:
!    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
!    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
!    * The names of the contributors may not be used to endorse or promote products derived from this software without specific prior written permission.

!THIS SOFTWARE IS PROVIDED BY Tom Schoonjans ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Tom Schoonjans BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



!Fortran 2003 bindings for xraylib
!By Tom Schoonjans (Tom.Schoonjans@UGent.be)

!Warning: can ony be compiled with Intel Fortran 10 or later, GFortran 4.3.0 or later and G95




      


MODULE xraylib

USE, INTRINSIC :: ISO_C_BINDING
IMPLICIT NONE

TYPE, BIND(C) :: compoundData_C
        INTEGER (C_INT) :: nElements
        INTEGER (C_INT) :: nAtomsAll
        TYPE (C_PTR) :: Elements
        TYPE (C_PTR) :: massFractions
ENDTYPE 

TYPE :: compoundData_F
        INTEGER (C_INT) :: nElements
        INTEGER (C_INT) :: nAtomsAll
        INTEGER (C_INT),DIMENSION(:),POINTER :: Elements
        REAL (C_DOUBLE),DIMENSION(:),POINTER :: massFractions
ENDTYPE 


!Constants


INTEGER (KIND=C_INT),PARAMETER ::  F1_TRANS   = 0
INTEGER (KIND=C_INT),PARAMETER ::  F12_TRANS  = 1
INTEGER (KIND=C_INT),PARAMETER ::  F13_TRANS  = 2
INTEGER (KIND=C_INT),PARAMETER ::  FP13_TRANS = 3
INTEGER (KIND=C_INT),PARAMETER ::  F23_TRANS  = 4

INTEGER (KIND=C_INT),PARAMETER ::  KA_LINE = 0
INTEGER (KIND=C_INT),PARAMETER ::  KB_LINE = 1
INTEGER (KIND=C_INT),PARAMETER ::  LA_LINE = 2
INTEGER (KIND=C_INT),PARAMETER ::  LB_LINE = 3

INTEGER (KIND=C_INT),PARAMETER :: KL1_LINE = -1
INTEGER (KIND=C_INT),PARAMETER :: KL2_LINE = -2
INTEGER (KIND=C_INT),PARAMETER :: KL3_LINE = -3
INTEGER (KIND=C_INT),PARAMETER :: KM1_LINE = -4
INTEGER (KIND=C_INT),PARAMETER :: KM2_LINE = -5
INTEGER (KIND=C_INT),PARAMETER :: KM3_LINE = -6
INTEGER (KIND=C_INT),PARAMETER :: KM4_LINE = -7
INTEGER (KIND=C_INT),PARAMETER :: KM5_LINE = -8
INTEGER (KIND=C_INT),PARAMETER :: KN1_LINE = -9
INTEGER (KIND=C_INT),PARAMETER :: KN2_LINE = -10
INTEGER (KIND=C_INT),PARAMETER :: KN3_LINE = -11
INTEGER (KIND=C_INT),PARAMETER :: KN4_LINE = -12
INTEGER (KIND=C_INT),PARAMETER :: KN5_LINE = -13
INTEGER (KIND=C_INT),PARAMETER :: KN6_LINE = -14
INTEGER (KIND=C_INT),PARAMETER :: KN7_LINE = -15
INTEGER (KIND=C_INT),PARAMETER :: KO_LINE = -16
INTEGER (KIND=C_INT),PARAMETER :: KO1_LINE = -17
INTEGER (KIND=C_INT),PARAMETER :: KO2_LINE = -18
INTEGER (KIND=C_INT),PARAMETER :: KO3_LINE = -19
INTEGER (KIND=C_INT),PARAMETER :: KO4_LINE = -20
INTEGER (KIND=C_INT),PARAMETER :: KO5_LINE = -21
INTEGER (KIND=C_INT),PARAMETER :: KO6_LINE = -22
INTEGER (KIND=C_INT),PARAMETER :: KO7_LINE = -23
INTEGER (KIND=C_INT),PARAMETER :: KP_LINE = -24
INTEGER (KIND=C_INT),PARAMETER :: KP1_LINE = -25
INTEGER (KIND=C_INT),PARAMETER :: KP2_LINE = -26
INTEGER (KIND=C_INT),PARAMETER :: KP3_LINE = -27
INTEGER (KIND=C_INT),PARAMETER :: KP4_LINE = -28
INTEGER (KIND=C_INT),PARAMETER :: KP5_LINE = -29
INTEGER (KIND=C_INT),PARAMETER :: L1L2_LINE = -30
INTEGER (KIND=C_INT),PARAMETER :: L1L3_LINE = -31
INTEGER (KIND=C_INT),PARAMETER :: L1M1_LINE = -32
INTEGER (KIND=C_INT),PARAMETER :: L1M2_LINE = -33
INTEGER (KIND=C_INT),PARAMETER :: L1M3_LINE = -34
INTEGER (KIND=C_INT),PARAMETER :: L1M4_LINE = -35
INTEGER (KIND=C_INT),PARAMETER :: L1M5_LINE = -36
INTEGER (KIND=C_INT),PARAMETER :: L1N1_LINE = -37
INTEGER (KIND=C_INT),PARAMETER :: L1N2_LINE = -38
INTEGER (KIND=C_INT),PARAMETER :: L1N3_LINE = -39
INTEGER (KIND=C_INT),PARAMETER :: L1N4_LINE = -40
INTEGER (KIND=C_INT),PARAMETER :: L1N5_LINE = -41
INTEGER (KIND=C_INT),PARAMETER :: L1N6_LINE = -42
INTEGER (KIND=C_INT),PARAMETER :: L1N67_LINE = -43
INTEGER (KIND=C_INT),PARAMETER :: L1N7_LINE = -44
INTEGER (KIND=C_INT),PARAMETER :: L1O1_LINE = -45
INTEGER (KIND=C_INT),PARAMETER :: L1O2_LINE = -46
INTEGER (KIND=C_INT),PARAMETER :: L1O3_LINE = -47
INTEGER (KIND=C_INT),PARAMETER :: L1O4_LINE = -48
INTEGER (KIND=C_INT),PARAMETER :: L1O45_LINE = -49
INTEGER (KIND=C_INT),PARAMETER :: L1O5_LINE = -50
INTEGER (KIND=C_INT),PARAMETER :: L1O6_LINE = -51
INTEGER (KIND=C_INT),PARAMETER :: L1O7_LINE = -52
INTEGER (KIND=C_INT),PARAMETER :: L1P1_LINE = -53
INTEGER (KIND=C_INT),PARAMETER :: L1P2_LINE = -54
INTEGER (KIND=C_INT),PARAMETER :: L1P23_LINE = -55
INTEGER (KIND=C_INT),PARAMETER :: L1P3_LINE = -56
INTEGER (KIND=C_INT),PARAMETER :: L1P4_LINE = -57
INTEGER (KIND=C_INT),PARAMETER :: L1P5_LINE = -58
INTEGER (KIND=C_INT),PARAMETER :: L2L3_LINE = -59
INTEGER (KIND=C_INT),PARAMETER :: L2M1_LINE = -60
INTEGER (KIND=C_INT),PARAMETER :: L2M2_LINE = -61
INTEGER (KIND=C_INT),PARAMETER :: L2M3_LINE = -62
INTEGER (KIND=C_INT),PARAMETER :: L2M4_LINE = -63
INTEGER (KIND=C_INT),PARAMETER :: L2M5_LINE = -64
INTEGER (KIND=C_INT),PARAMETER :: L2N1_LINE = -65
INTEGER (KIND=C_INT),PARAMETER :: L2N2_LINE = -66
INTEGER (KIND=C_INT),PARAMETER :: L2N3_LINE = -67
INTEGER (KIND=C_INT),PARAMETER :: L2N4_LINE = -68
INTEGER (KIND=C_INT),PARAMETER :: L2N5_LINE = -69
INTEGER (KIND=C_INT),PARAMETER :: L2N6_LINE = -70
INTEGER (KIND=C_INT),PARAMETER :: L2N7_LINE = -71
INTEGER (KIND=C_INT),PARAMETER :: L2O1_LINE = -72
INTEGER (KIND=C_INT),PARAMETER :: L2O2_LINE = -73
INTEGER (KIND=C_INT),PARAMETER :: L2O3_LINE = -74
INTEGER (KIND=C_INT),PARAMETER :: L2O4_LINE = -75
INTEGER (KIND=C_INT),PARAMETER :: L2O5_LINE = -76
INTEGER (KIND=C_INT),PARAMETER :: L2O6_LINE = -77
INTEGER (KIND=C_INT),PARAMETER :: L2O7_LINE = -78
INTEGER (KIND=C_INT),PARAMETER :: L2P1_LINE = -79
INTEGER (KIND=C_INT),PARAMETER :: L2P2_LINE = -80
INTEGER (KIND=C_INT),PARAMETER :: L2P23_LINE = -81
INTEGER (KIND=C_INT),PARAMETER :: L2P3_LINE = -82
INTEGER (KIND=C_INT),PARAMETER :: L2P4_LINE = -83
INTEGER (KIND=C_INT),PARAMETER :: L2P5_LINE = -84
INTEGER (KIND=C_INT),PARAMETER :: L2Q1_LINE = -85
INTEGER (KIND=C_INT),PARAMETER :: L3M1_LINE = -86
INTEGER (KIND=C_INT),PARAMETER :: L3M2_LINE = -87
INTEGER (KIND=C_INT),PARAMETER :: L3M3_LINE = -88
INTEGER (KIND=C_INT),PARAMETER :: L3M4_LINE = -89
INTEGER (KIND=C_INT),PARAMETER :: L3M5_LINE = -90
INTEGER (KIND=C_INT),PARAMETER :: L3N1_LINE = -91
INTEGER (KIND=C_INT),PARAMETER :: L3N2_LINE = -92
INTEGER (KIND=C_INT),PARAMETER :: L3N3_LINE = -93
INTEGER (KIND=C_INT),PARAMETER :: L3N4_LINE = -94
INTEGER (KIND=C_INT),PARAMETER :: L3N5_LINE = -95
INTEGER (KIND=C_INT),PARAMETER :: L3N6_LINE = -96
INTEGER (KIND=C_INT),PARAMETER :: L3N7_LINE = -97
INTEGER (KIND=C_INT),PARAMETER :: L3O1_LINE = -98
INTEGER (KIND=C_INT),PARAMETER :: L3O2_LINE = -99
INTEGER (KIND=C_INT),PARAMETER :: L3O3_LINE = -100
INTEGER (KIND=C_INT),PARAMETER :: L3O4_LINE = -101
INTEGER (KIND=C_INT),PARAMETER :: L3O45_LINE = -102
INTEGER (KIND=C_INT),PARAMETER :: L3O5_LINE = -103
INTEGER (KIND=C_INT),PARAMETER :: L3O6_LINE = -104
INTEGER (KIND=C_INT),PARAMETER :: L3O7_LINE = -105
INTEGER (KIND=C_INT),PARAMETER :: L3P1_LINE = -106
INTEGER (KIND=C_INT),PARAMETER :: L3P2_LINE = -107
INTEGER (KIND=C_INT),PARAMETER :: L3P23_LINE = -108
INTEGER (KIND=C_INT),PARAMETER :: L3P3_LINE = -109
INTEGER (KIND=C_INT),PARAMETER :: L3P4_LINE = -110
INTEGER (KIND=C_INT),PARAMETER :: L3P45_LINE = -111
INTEGER (KIND=C_INT),PARAMETER :: L3P5_LINE = -112
INTEGER (KIND=C_INT),PARAMETER :: L3Q1_LINE = -113
INTEGER (KIND=C_INT),PARAMETER :: M1M2_LINE = -114
INTEGER (KIND=C_INT),PARAMETER :: M1M3_LINE = -115
INTEGER (KIND=C_INT),PARAMETER :: M1M4_LINE = -116
INTEGER (KIND=C_INT),PARAMETER :: M1M5_LINE = -117
INTEGER (KIND=C_INT),PARAMETER :: M1N1_LINE = -118
INTEGER (KIND=C_INT),PARAMETER :: M1N2_LINE = -119
INTEGER (KIND=C_INT),PARAMETER :: M1N3_LINE = -120
INTEGER (KIND=C_INT),PARAMETER :: M1N4_LINE = -121
INTEGER (KIND=C_INT),PARAMETER :: M1N5_LINE = -122
INTEGER (KIND=C_INT),PARAMETER :: M1N6_LINE = -123
INTEGER (KIND=C_INT),PARAMETER :: M1N7_LINE = -124
INTEGER (KIND=C_INT),PARAMETER :: M1O1_LINE = -125
INTEGER (KIND=C_INT),PARAMETER :: M1O2_LINE = -126
INTEGER (KIND=C_INT),PARAMETER :: M1O3_LINE = -127
INTEGER (KIND=C_INT),PARAMETER :: M1O4_LINE = -128
INTEGER (KIND=C_INT),PARAMETER :: M1O5_LINE = -129
INTEGER (KIND=C_INT),PARAMETER :: M1O6_LINE = -130
INTEGER (KIND=C_INT),PARAMETER :: M1O7_LINE = -131
INTEGER (KIND=C_INT),PARAMETER :: M1P1_LINE = -132
INTEGER (KIND=C_INT),PARAMETER :: M1P2_LINE = -133
INTEGER (KIND=C_INT),PARAMETER :: M1P3_LINE = -134
INTEGER (KIND=C_INT),PARAMETER :: M1P4_LINE = -135
INTEGER (KIND=C_INT),PARAMETER :: M1P5_LINE = -136
INTEGER (KIND=C_INT),PARAMETER :: M2M3_LINE = -137
INTEGER (KIND=C_INT),PARAMETER :: M2M4_LINE = -138
INTEGER (KIND=C_INT),PARAMETER :: M2M5_LINE = -139
INTEGER (KIND=C_INT),PARAMETER :: M2N1_LINE = -140
INTEGER (KIND=C_INT),PARAMETER :: M2N2_LINE = -141
INTEGER (KIND=C_INT),PARAMETER :: M2N3_LINE = -142
INTEGER (KIND=C_INT),PARAMETER :: M2N4_LINE = -143
INTEGER (KIND=C_INT),PARAMETER :: M2N5_LINE = -144
INTEGER (KIND=C_INT),PARAMETER :: M2N6_LINE = -145
INTEGER (KIND=C_INT),PARAMETER :: M2N7_LINE = -146
INTEGER (KIND=C_INT),PARAMETER :: M2O1_LINE = -147
INTEGER (KIND=C_INT),PARAMETER :: M2O2_LINE = -148
INTEGER (KIND=C_INT),PARAMETER :: M2O3_LINE = -149
INTEGER (KIND=C_INT),PARAMETER :: M2O4_LINE = -150
INTEGER (KIND=C_INT),PARAMETER :: M2O5_LINE = -151
INTEGER (KIND=C_INT),PARAMETER :: M2O6_LINE = -152
INTEGER (KIND=C_INT),PARAMETER :: M2O7_LINE = -153
INTEGER (KIND=C_INT),PARAMETER :: M2P1_LINE = -154
INTEGER (KIND=C_INT),PARAMETER :: M2P2_LINE = -155
INTEGER (KIND=C_INT),PARAMETER :: M2P3_LINE = -156
INTEGER (KIND=C_INT),PARAMETER :: M2P4_LINE = -157
INTEGER (KIND=C_INT),PARAMETER :: M2P5_LINE = -158
INTEGER (KIND=C_INT),PARAMETER :: M3M4_LINE = -159
INTEGER (KIND=C_INT),PARAMETER :: M3M5_LINE = -160
INTEGER (KIND=C_INT),PARAMETER :: M3N1_LINE = -161
INTEGER (KIND=C_INT),PARAMETER :: M3N2_LINE = -162
INTEGER (KIND=C_INT),PARAMETER :: M3N3_LINE = -163
INTEGER (KIND=C_INT),PARAMETER :: M3N4_LINE = -164
INTEGER (KIND=C_INT),PARAMETER :: M3N5_LINE = -165
INTEGER (KIND=C_INT),PARAMETER :: M3N6_LINE = -166
INTEGER (KIND=C_INT),PARAMETER :: M3N7_LINE = -167
INTEGER (KIND=C_INT),PARAMETER :: M3O1_LINE = -168
INTEGER (KIND=C_INT),PARAMETER :: M3O2_LINE = -169
INTEGER (KIND=C_INT),PARAMETER :: M3O3_LINE = -170
INTEGER (KIND=C_INT),PARAMETER :: M3O4_LINE = -171
INTEGER (KIND=C_INT),PARAMETER :: M3O5_LINE = -172
INTEGER (KIND=C_INT),PARAMETER :: M3O6_LINE = -173
INTEGER (KIND=C_INT),PARAMETER :: M3O7_LINE = -174
INTEGER (KIND=C_INT),PARAMETER :: M3P1_LINE = -175
INTEGER (KIND=C_INT),PARAMETER :: M3P2_LINE = -176
INTEGER (KIND=C_INT),PARAMETER :: M3P3_LINE = -177
INTEGER (KIND=C_INT),PARAMETER :: M3P4_LINE = -178
INTEGER (KIND=C_INT),PARAMETER :: M3P5_LINE = -179
INTEGER (KIND=C_INT),PARAMETER :: M3Q1_LINE = -180
INTEGER (KIND=C_INT),PARAMETER :: M4M5_LINE = -181
INTEGER (KIND=C_INT),PARAMETER :: M4N1_LINE = -182
INTEGER (KIND=C_INT),PARAMETER :: M4N2_LINE = -183
INTEGER (KIND=C_INT),PARAMETER :: M4N3_LINE = -184
INTEGER (KIND=C_INT),PARAMETER :: M4N4_LINE = -185
INTEGER (KIND=C_INT),PARAMETER :: M4N5_LINE = -186
INTEGER (KIND=C_INT),PARAMETER :: M4N6_LINE = -187
INTEGER (KIND=C_INT),PARAMETER :: M4N7_LINE = -188
INTEGER (KIND=C_INT),PARAMETER :: M4O1_LINE = -189
INTEGER (KIND=C_INT),PARAMETER :: M4O2_LINE = -190
INTEGER (KIND=C_INT),PARAMETER :: M4O3_LINE = -191
INTEGER (KIND=C_INT),PARAMETER :: M4O4_LINE = -192
INTEGER (KIND=C_INT),PARAMETER :: M4O5_LINE = -193
INTEGER (KIND=C_INT),PARAMETER :: M4O6_LINE = -194
INTEGER (KIND=C_INT),PARAMETER :: M4O7_LINE = -195
INTEGER (KIND=C_INT),PARAMETER :: M4P1_LINE = -196
INTEGER (KIND=C_INT),PARAMETER :: M4P2_LINE = -197
INTEGER (KIND=C_INT),PARAMETER :: M4P3_LINE = -198
INTEGER (KIND=C_INT),PARAMETER :: M4P4_LINE = -199
INTEGER (KIND=C_INT),PARAMETER :: M4P5_LINE = -200
INTEGER (KIND=C_INT),PARAMETER :: M5N1_LINE = -201
INTEGER (KIND=C_INT),PARAMETER :: M5N2_LINE = -202
INTEGER (KIND=C_INT),PARAMETER :: M5N3_LINE = -203
INTEGER (KIND=C_INT),PARAMETER :: M5N4_LINE = -204
INTEGER (KIND=C_INT),PARAMETER :: M5N5_LINE = -205
INTEGER (KIND=C_INT),PARAMETER :: M5N6_LINE = -206
INTEGER (KIND=C_INT),PARAMETER :: M5N7_LINE = -207
INTEGER (KIND=C_INT),PARAMETER :: M5O1_LINE = -208
INTEGER (KIND=C_INT),PARAMETER :: M5O2_LINE = -209
INTEGER (KIND=C_INT),PARAMETER :: M5O3_LINE = -210
INTEGER (KIND=C_INT),PARAMETER :: M5O4_LINE = -211
INTEGER (KIND=C_INT),PARAMETER :: M5O5_LINE = -212
INTEGER (KIND=C_INT),PARAMETER :: M5O6_LINE = -213
INTEGER (KIND=C_INT),PARAMETER :: M5O7_LINE = -214
INTEGER (KIND=C_INT),PARAMETER :: M5P1_LINE = -215
INTEGER (KIND=C_INT),PARAMETER :: M5P2_LINE = -216
INTEGER (KIND=C_INT),PARAMETER :: M5P3_LINE = -217
INTEGER (KIND=C_INT),PARAMETER :: M5P4_LINE = -218
INTEGER (KIND=C_INT),PARAMETER :: M5P5_LINE = -219
INTEGER (KIND=C_INT),PARAMETER :: N1N2_LINE = -220
INTEGER (KIND=C_INT),PARAMETER :: N1N3_LINE = -221
INTEGER (KIND=C_INT),PARAMETER :: N1N4_LINE = -222
INTEGER (KIND=C_INT),PARAMETER :: N1N5_LINE = -223
INTEGER (KIND=C_INT),PARAMETER :: N1N6_LINE = -224
INTEGER (KIND=C_INT),PARAMETER :: N1N7_LINE = -225
INTEGER (KIND=C_INT),PARAMETER :: N1O1_LINE = -226
INTEGER (KIND=C_INT),PARAMETER :: N1O2_LINE = -227
INTEGER (KIND=C_INT),PARAMETER :: N1O3_LINE = -228
INTEGER (KIND=C_INT),PARAMETER :: N1O4_LINE = -229
INTEGER (KIND=C_INT),PARAMETER :: N1O5_LINE = -230
INTEGER (KIND=C_INT),PARAMETER :: N1O6_LINE = -231
INTEGER (KIND=C_INT),PARAMETER :: N1O7_LINE = -232
INTEGER (KIND=C_INT),PARAMETER :: N1P1_LINE = -233
INTEGER (KIND=C_INT),PARAMETER :: N1P2_LINE = -234
INTEGER (KIND=C_INT),PARAMETER :: N1P3_LINE = -235
INTEGER (KIND=C_INT),PARAMETER :: N1P4_LINE = -236
INTEGER (KIND=C_INT),PARAMETER :: N1P5_LINE = -237
INTEGER (KIND=C_INT),PARAMETER :: N2N3_LINE = -238
INTEGER (KIND=C_INT),PARAMETER :: N2N4_LINE = -239
INTEGER (KIND=C_INT),PARAMETER :: N2N5_LINE = -240
INTEGER (KIND=C_INT),PARAMETER :: N2N6_LINE = -241
INTEGER (KIND=C_INT),PARAMETER :: N2N7_LINE = -242
INTEGER (KIND=C_INT),PARAMETER :: N2O1_LINE = -243
INTEGER (KIND=C_INT),PARAMETER :: N2O2_LINE = -244
INTEGER (KIND=C_INT),PARAMETER :: N2O3_LINE = -245
INTEGER (KIND=C_INT),PARAMETER :: N2O4_LINE = -246
INTEGER (KIND=C_INT),PARAMETER :: N2O5_LINE = -247
INTEGER (KIND=C_INT),PARAMETER :: N2O6_LINE = -248
INTEGER (KIND=C_INT),PARAMETER :: N2O7_LINE = -249
INTEGER (KIND=C_INT),PARAMETER :: N2P1_LINE = -250
INTEGER (KIND=C_INT),PARAMETER :: N2P2_LINE = -251
INTEGER (KIND=C_INT),PARAMETER :: N2P3_LINE = -252
INTEGER (KIND=C_INT),PARAMETER :: N2P4_LINE = -253
INTEGER (KIND=C_INT),PARAMETER :: N2P5_LINE = -254
INTEGER (KIND=C_INT),PARAMETER :: N3N4_LINE = -255
INTEGER (KIND=C_INT),PARAMETER :: N3N5_LINE = -256
INTEGER (KIND=C_INT),PARAMETER :: N3N6_LINE = -257
INTEGER (KIND=C_INT),PARAMETER :: N3N7_LINE = -258
INTEGER (KIND=C_INT),PARAMETER :: N3O1_LINE = -259
INTEGER (KIND=C_INT),PARAMETER :: N3O2_LINE = -260
INTEGER (KIND=C_INT),PARAMETER :: N3O3_LINE = -261
INTEGER (KIND=C_INT),PARAMETER :: N3O4_LINE = -262
INTEGER (KIND=C_INT),PARAMETER :: N3O5_LINE = -263
INTEGER (KIND=C_INT),PARAMETER :: N3O6_LINE = -264
INTEGER (KIND=C_INT),PARAMETER :: N3O7_LINE = -265
INTEGER (KIND=C_INT),PARAMETER :: N3P1_LINE = -266
INTEGER (KIND=C_INT),PARAMETER :: N3P2_LINE = -267
INTEGER (KIND=C_INT),PARAMETER :: N3P3_LINE = -268
INTEGER (KIND=C_INT),PARAMETER :: N3P4_LINE = -269
INTEGER (KIND=C_INT),PARAMETER :: N3P5_LINE = -270
INTEGER (KIND=C_INT),PARAMETER :: N4N5_LINE = -271
INTEGER (KIND=C_INT),PARAMETER :: N4N6_LINE = -272
INTEGER (KIND=C_INT),PARAMETER :: N4N7_LINE = -273
INTEGER (KIND=C_INT),PARAMETER :: N4O1_LINE = -274
INTEGER (KIND=C_INT),PARAMETER :: N4O2_LINE = -275
INTEGER (KIND=C_INT),PARAMETER :: N4O3_LINE = -276
INTEGER (KIND=C_INT),PARAMETER :: N4O4_LINE = -277
INTEGER (KIND=C_INT),PARAMETER :: N4O5_LINE = -278
INTEGER (KIND=C_INT),PARAMETER :: N4O6_LINE = -279
INTEGER (KIND=C_INT),PARAMETER :: N4O7_LINE = -280
INTEGER (KIND=C_INT),PARAMETER :: N4P1_LINE = -281
INTEGER (KIND=C_INT),PARAMETER :: N4P2_LINE = -282
INTEGER (KIND=C_INT),PARAMETER :: N4P3_LINE = -283
INTEGER (KIND=C_INT),PARAMETER :: N4P4_LINE = -284
INTEGER (KIND=C_INT),PARAMETER :: N4P5_LINE = -285
INTEGER (KIND=C_INT),PARAMETER :: N5N6_LINE = -286
INTEGER (KIND=C_INT),PARAMETER :: N5N7_LINE = -287
INTEGER (KIND=C_INT),PARAMETER :: N5O1_LINE = -288
INTEGER (KIND=C_INT),PARAMETER :: N5O2_LINE = -289
INTEGER (KIND=C_INT),PARAMETER :: N5O3_LINE = -290
INTEGER (KIND=C_INT),PARAMETER :: N5O4_LINE = -291
INTEGER (KIND=C_INT),PARAMETER :: N5O5_LINE = -292
INTEGER (KIND=C_INT),PARAMETER :: N5O6_LINE = -293
INTEGER (KIND=C_INT),PARAMETER :: N5O7_LINE = -294
INTEGER (KIND=C_INT),PARAMETER :: N5P1_LINE = -295
INTEGER (KIND=C_INT),PARAMETER :: N5P2_LINE = -296
INTEGER (KIND=C_INT),PARAMETER :: N5P3_LINE = -297
INTEGER (KIND=C_INT),PARAMETER :: N5P4_LINE = -298
INTEGER (KIND=C_INT),PARAMETER :: N5P5_LINE = -299
INTEGER (KIND=C_INT),PARAMETER :: N6N7_LINE = -300
INTEGER (KIND=C_INT),PARAMETER :: N6O1_LINE = -301
INTEGER (KIND=C_INT),PARAMETER :: N6O2_LINE = -302
INTEGER (KIND=C_INT),PARAMETER :: N6O3_LINE = -303
INTEGER (KIND=C_INT),PARAMETER :: N6O4_LINE = -304
INTEGER (KIND=C_INT),PARAMETER :: N6O5_LINE = -305
INTEGER (KIND=C_INT),PARAMETER :: N6O6_LINE = -306
INTEGER (KIND=C_INT),PARAMETER :: N6O7_LINE = -307
INTEGER (KIND=C_INT),PARAMETER :: N6P1_LINE = -308
INTEGER (KIND=C_INT),PARAMETER :: N6P2_LINE = -309
INTEGER (KIND=C_INT),PARAMETER :: N6P3_LINE = -310
INTEGER (KIND=C_INT),PARAMETER :: N6P4_LINE = -311
INTEGER (KIND=C_INT),PARAMETER :: N6P5_LINE = -312
INTEGER (KIND=C_INT),PARAMETER :: N7O1_LINE = -313
INTEGER (KIND=C_INT),PARAMETER :: N7O2_LINE = -314
INTEGER (KIND=C_INT),PARAMETER :: N7O3_LINE = -315
INTEGER (KIND=C_INT),PARAMETER :: N7O4_LINE = -316
INTEGER (KIND=C_INT),PARAMETER :: N7O5_LINE = -317
INTEGER (KIND=C_INT),PARAMETER :: N7O6_LINE = -318
INTEGER (KIND=C_INT),PARAMETER :: N7O7_LINE = -319
INTEGER (KIND=C_INT),PARAMETER :: N7P1_LINE = -320
INTEGER (KIND=C_INT),PARAMETER :: N7P2_LINE = -321
INTEGER (KIND=C_INT),PARAMETER :: N7P3_LINE = -322
INTEGER (KIND=C_INT),PARAMETER :: N7P4_LINE = -323
INTEGER (KIND=C_INT),PARAMETER :: N7P5_LINE = -324
INTEGER (KIND=C_INT),PARAMETER :: O1O2_LINE = -325
INTEGER (KIND=C_INT),PARAMETER :: O1O3_LINE = -326
INTEGER (KIND=C_INT),PARAMETER :: O1O4_LINE = -327
INTEGER (KIND=C_INT),PARAMETER :: O1O5_LINE = -328
INTEGER (KIND=C_INT),PARAMETER :: O1O6_LINE = -329
INTEGER (KIND=C_INT),PARAMETER :: O1O7_LINE = -330
INTEGER (KIND=C_INT),PARAMETER :: O1P1_LINE = -331
INTEGER (KIND=C_INT),PARAMETER :: O1P2_LINE = -332
INTEGER (KIND=C_INT),PARAMETER :: O1P3_LINE = -333
INTEGER (KIND=C_INT),PARAMETER :: O1P4_LINE = -334
INTEGER (KIND=C_INT),PARAMETER :: O1P5_LINE = -335
INTEGER (KIND=C_INT),PARAMETER :: O2O3_LINE = -336
INTEGER (KIND=C_INT),PARAMETER :: O2O4_LINE = -337
INTEGER (KIND=C_INT),PARAMETER :: O2O5_LINE = -338
INTEGER (KIND=C_INT),PARAMETER :: O2O6_LINE = -339
INTEGER (KIND=C_INT),PARAMETER :: O2O7_LINE = -340
INTEGER (KIND=C_INT),PARAMETER :: O2P1_LINE = -341
INTEGER (KIND=C_INT),PARAMETER :: O2P2_LINE = -342
INTEGER (KIND=C_INT),PARAMETER :: O2P3_LINE = -343
INTEGER (KIND=C_INT),PARAMETER :: O2P4_LINE = -344
INTEGER (KIND=C_INT),PARAMETER :: O2P5_LINE = -345
INTEGER (KIND=C_INT),PARAMETER :: O3O4_LINE = -346
INTEGER (KIND=C_INT),PARAMETER :: O3O5_LINE = -347
INTEGER (KIND=C_INT),PARAMETER :: O3O6_LINE = -348
INTEGER (KIND=C_INT),PARAMETER :: O3O7_LINE = -349
INTEGER (KIND=C_INT),PARAMETER :: O3P1_LINE = -350
INTEGER (KIND=C_INT),PARAMETER :: O3P2_LINE = -351
INTEGER (KIND=C_INT),PARAMETER :: O3P3_LINE = -352
INTEGER (KIND=C_INT),PARAMETER :: O3P4_LINE = -353
INTEGER (KIND=C_INT),PARAMETER :: O3P5_LINE = -354
INTEGER (KIND=C_INT),PARAMETER :: O4O5_LINE = -355
INTEGER (KIND=C_INT),PARAMETER :: O4O6_LINE = -356
INTEGER (KIND=C_INT),PARAMETER :: O4O7_LINE = -357
INTEGER (KIND=C_INT),PARAMETER :: O4P1_LINE = -358
INTEGER (KIND=C_INT),PARAMETER :: O4P2_LINE = -359
INTEGER (KIND=C_INT),PARAMETER :: O4P3_LINE = -360
INTEGER (KIND=C_INT),PARAMETER :: O4P4_LINE = -361
INTEGER (KIND=C_INT),PARAMETER :: O4P5_LINE = -362
INTEGER (KIND=C_INT),PARAMETER :: O5O6_LINE = -363
INTEGER (KIND=C_INT),PARAMETER :: O5O7_LINE = -364
INTEGER (KIND=C_INT),PARAMETER :: O5P1_LINE = -365
INTEGER (KIND=C_INT),PARAMETER :: O5P2_LINE = -366
INTEGER (KIND=C_INT),PARAMETER :: O5P3_LINE = -367
INTEGER (KIND=C_INT),PARAMETER :: O5P4_LINE = -368
INTEGER (KIND=C_INT),PARAMETER :: O5P5_LINE = -369
INTEGER (KIND=C_INT),PARAMETER :: O6O7_LINE = -370
INTEGER (KIND=C_INT),PARAMETER :: O6P4_LINE = -371
INTEGER (KIND=C_INT),PARAMETER :: O6P5_LINE = -372
INTEGER (KIND=C_INT),PARAMETER :: O7P4_LINE = -373
INTEGER (KIND=C_INT),PARAMETER :: O7P5_LINE = -374
INTEGER (KIND=C_INT),PARAMETER :: P1P2_LINE = -375
INTEGER (KIND=C_INT),PARAMETER :: P1P3_LINE = -376
INTEGER (KIND=C_INT),PARAMETER :: P1P4_LINE = -377
INTEGER (KIND=C_INT),PARAMETER :: P1P5_LINE = -378
INTEGER (KIND=C_INT),PARAMETER :: P2P3_LINE = -379
INTEGER (KIND=C_INT),PARAMETER :: P2P4_LINE = -380
INTEGER (KIND=C_INT),PARAMETER :: P2P5_LINE = -381
INTEGER (KIND=C_INT),PARAMETER :: P3P4_LINE = -382
INTEGER (KIND=C_INT),PARAMETER :: P3P5_LINE = -383



INTEGER (KIND=C_INT),PARAMETER ::  K_SHELL = 0
INTEGER (KIND=C_INT),PARAMETER ::  L1_SHELL = 1
INTEGER (KIND=C_INT),PARAMETER ::  L2_SHELL = 2
INTEGER (KIND=C_INT),PARAMETER ::  L3_SHELL = 3
INTEGER (KIND=C_INT),PARAMETER ::  M1_SHELL = 4
INTEGER (KIND=C_INT),PARAMETER ::  M2_SHELL = 5
INTEGER (KIND=C_INT),PARAMETER ::  M3_SHELL = 6
INTEGER (KIND=C_INT),PARAMETER ::  M4_SHELL = 7
INTEGER (KIND=C_INT),PARAMETER ::  M5_SHELL = 8
INTEGER (KIND=C_INT),PARAMETER ::  N1_SHELL = 9
INTEGER (KIND=C_INT),PARAMETER ::  N2_SHELL = 10
INTEGER (KIND=C_INT),PARAMETER ::  N3_SHELL = 11
INTEGER (KIND=C_INT),PARAMETER ::  N4_SHELL = 12
INTEGER (KIND=C_INT),PARAMETER ::  N5_SHELL = 13
INTEGER (KIND=C_INT),PARAMETER ::  N6_SHELL = 14
INTEGER (KIND=C_INT),PARAMETER ::  N7_SHELL = 15
INTEGER (KIND=C_INT),PARAMETER ::  O1_SHELL = 16
INTEGER (KIND=C_INT),PARAMETER ::  O2_SHELL = 17
INTEGER (KIND=C_INT),PARAMETER ::  O3_SHELL = 18
INTEGER (KIND=C_INT),PARAMETER ::  O4_SHELL = 19
INTEGER (KIND=C_INT),PARAMETER ::  O5_SHELL = 20
INTEGER (KIND=C_INT),PARAMETER ::  O6_SHELL = 21
INTEGER (KIND=C_INT),PARAMETER ::  O7_SHELL = 22
INTEGER (KIND=C_INT),PARAMETER ::  P1_SHELL = 23
INTEGER (KIND=C_INT),PARAMETER ::  P2_SHELL = 24
INTEGER (KIND=C_INT),PARAMETER ::  P3_SHELL = 25
INTEGER (KIND=C_INT),PARAMETER ::  P4_SHELL = 26
INTEGER (KIND=C_INT),PARAMETER ::  P5_SHELL = 27
INTEGER (KIND=C_INT),PARAMETER ::  Q1_SHELL = 28
INTEGER (KIND=C_INT),PARAMETER ::  Q2_SHELL = 29
INTEGER (KIND=C_INT),PARAMETER ::  Q3_SHELL = 30

INTEGER (KIND=C_INT),PARAMETER ::  KA1_LINE = KL3_LINE
INTEGER (KIND=C_INT),PARAMETER ::  KA2_LINE = KL2_LINE
INTEGER (KIND=C_INT),PARAMETER ::  KB1_LINE = KM3_LINE
INTEGER (KIND=C_INT),PARAMETER ::  KB2_LINE = KN3_LINE
INTEGER (KIND=C_INT),PARAMETER ::  KB3_LINE = KM2_LINE
INTEGER (KIND=C_INT),PARAMETER ::  KB4_LINE = KN5_LINE
INTEGER (KIND=C_INT),PARAMETER ::  KB5_LINE = KM5_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LA1_LINE = L3M5_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LA2_LINE = L3M4_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB1_LINE = L2M4_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB2_LINE = L3N5_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB3_LINE = L1M3_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB4_LINE = L1M2_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB5_LINE = L3O45_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB6_LINE = L3N1_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB7_LINE = L3O1_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB9_LINE = L1M5_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB10_LINE = L1M4_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB15_LINE = L3N4_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LB17_LINE = L2M3_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LG1_LINE = L2N4_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LG2_LINE = L1N2_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LG3_LINE = L1N3_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LG4_LINE = L1O3_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LG5_LINE = L2N1_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LG6_LINE = L2O4_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LG8_LINE = L2O1_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LE_LINE = L2M1_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LL_LINE = L3M1_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LS_LINE = L3M3_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LT_LINE = L3M2_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LU_LINE = L3N6_LINE
INTEGER (KIND=C_INT),PARAMETER ::  LV_LINE = L2N6_LINE
INTEGER (KIND=C_INT),PARAMETER ::  MA1_LINE = M5N7_LINE
INTEGER (KIND=C_INT),PARAMETER ::  MA2_LINE = M5N6_LINE
INTEGER (KIND=C_INT),PARAMETER ::  MB_LINE = M4N6_LINE
INTEGER (KIND=C_INT),PARAMETER ::  MG_LINE = M3N5_LINE



INTERFACE
!All procedures are pure

	!Initialization
	SUBROUTINE XRayInit() BIND(C,NAME='XRayInit')
	ENDSUBROUTINE XRayInit

	!Error handling
	PURE SUBROUTINE SetHardExit(hard_exit) BIND(C,NAME='SetHardExit')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
		INTEGER (KIND=C_INT),INTENT(IN),VALUE :: hard_exit
	ENDSUBROUTINE SetHardExit

	PURE SUBROUTINE SetExitStatus(exit_status) BIND(C,NAME='SetExitStatus')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
		INTEGER (KIND=C_INT),INTENT(IN),VALUE :: exit_status
	ENDSUBROUTINE SetExitStatus

	PURE FUNCTION GetExitStatus() BIND(C,NAME='GetExitStatus')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
		INTEGER (KIND=C_INT) :: GetExitStatus
	ENDFUNCTION

	!Atomic Weights
        PURE FUNCTION AtomicWeight(Z) BIND(C,NAME='AtomicWeight')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: AtomicWeight
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
        END FUNCTION AtomicWeight

	!Cross sections (cm2/g)
        PURE FUNCTION CS_Total(Z,E) BIND(C,NAME='CS_Total')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_Total
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E
        END FUNCTION CS_Total

        PURE FUNCTION CS_Photo(Z,E) BIND(C,NAME='CS_Photo')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_Photo
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CS_Photo

        PURE FUNCTION CS_Rayl(Z,E) BIND(C,NAME='CS_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_Rayl
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CS_Rayl

        PURE FUNCTION CS_Compt(Z,E) BIND(C,NAME='CS_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_Compt
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CS_Compt

        PURE FUNCTION CS_KN(E) BIND(C,NAME='CS_KN')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_KN
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CS_KN

	!Cross sections (barn/atom)
        PURE FUNCTION CSb_Total(Z,E) BIND(C,NAME='CSb_Total')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_Total
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E
        END FUNCTION CSb_Total

        PURE FUNCTION CSb_Photo(Z,E) BIND(C,NAME='CSb_Photo')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_Photo
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CSb_Photo

        PURE FUNCTION CSb_Rayl(Z,E) BIND(C,NAME='CSb_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_Rayl
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CSb_Rayl

        PURE FUNCTION CSb_Compt(Z,E) BIND(C,NAME='CSb_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_Compt
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CSb_Compt

	!Unpolarized differential scattering cross sections
	PURE FUNCTION DCS_Thoms(theta) BIND(C,NAME='DCS_Thoms')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCS_Thoms
		REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: theta
	ENDFUNCTION DCS_Thoms

	PURE FUNCTION DCS_KN(E ,theta) BIND(C,NAME='DCS_KN')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCS_KN
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E, theta
	ENDFUNCTION DCS_KN

	PURE FUNCTION DCS_Rayl(Z ,E ,theta) BIND(C,NAME='DCS_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCS_Rayl
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E,theta
	ENDFUNCTION DCS_Rayl

	PURE FUNCTION DCS_Compt(Z ,E ,theta) BIND(C,NAME='DCS_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCS_Compt
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E,theta
	ENDFUNCTION DCS_Compt

	PURE FUNCTION DCSb_Rayl(Z ,E ,theta) BIND(C,NAME='DCSb_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSb_Rayl
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E,theta
	ENDFUNCTION DCSb_Rayl

	PURE FUNCTION DCSb_Compt(Z ,E ,theta) BIND(C,NAME='DCSb_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSb_Compt
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E,theta
	ENDFUNCTION DCSb_Compt

	!Polarized differential scattering cross sections
	PURE FUNCTION DCSP_Thoms(theta, phi) BIND(C,NAME='DCSP_Thoms')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSP_Thoms
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: theta, phi
	ENDFUNCTION DCSP_Thoms

	PURE FUNCTION DCSP_KN(E, theta, phi) BIND(C,NAME='DCSP_KN')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSP_KN
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSP_KN

	PURE FUNCTION DCSP_Rayl(Z, E, theta, phi) BIND(C,NAME='DCSP_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSP_Rayl
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSP_Rayl

	PURE FUNCTION DCSP_Compt(Z, E, theta, phi) BIND(C,NAME='DCSP_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSP_Compt
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSP_Compt

	PURE FUNCTION DCSPb_Rayl(Z, E, theta, phi) BIND(C,NAME='DCSPb_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSPb_Rayl
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSPb_Rayl

	PURE FUNCTION DCSPb_Compt(Z, E, theta, phi) BIND(C,NAME='DCSPb_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSPb_Compt
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSPb_Compt
	
	!Scattering factors
	PURE FUNCTION FF_Rayl(Z , q) BIND(C,NAME='FF_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: FF_Rayl
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: q
	ENDFUNCTION FF_Rayl

	PURE FUNCTION SF_Compt(Z , q) BIND(C,NAME='SF_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: SF_Compt
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: q
	ENDFUNCTION SF_Compt

	PURE FUNCTION MomentTransf(E , theta) BIND(C,NAME='MomentTransf')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: MomentTransf
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E , theta
	ENDFUNCTION

	!X-ray fluorescent line energy
        PURE FUNCTION LineEnergy(Z,line) BIND(C,NAME='LineEnergy')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: LineEnergy
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z,line
        END FUNCTION LineEnergy

	!Fluorescence yield
        PURE FUNCTION FluorYield(Z,shell) BIND(C,NAME='FluorYield')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: FluorYield
                INTEGER (KIND=C_INT),INTENT(IN),VALUE ::Z,shell
        END FUNCTION FluorYield

	!Coster-Kronig transition probability
        PURE FUNCTION CosKronTransProb(Z,trans) &
		BIND(C,NAME='CosKronTransProb')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CosKronTransProb
                INTEGER (KIND=C_INT),INTENT(IN),VALUE ::Z,trans
        END FUNCTION CosKronTransProb

	!Absorption-edge energies
        PURE FUNCTION EdgeEnergy(Z,shell) BIND(C,NAME='EdgeEnergy')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: EdgeEnergy
                INTEGER (KIND=C_INT),INTENT(IN),VALUE ::Z,shell
        END FUNCTION EdgeEnergy

	!Jump ratios
        PURE FUNCTION JumpFactor(Z,shell) BIND(C,NAME='JumpFactor')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: JumpFactor
                INTEGER (KIND=C_INT),INTENT(IN),VALUE ::Z,shell
        END FUNCTION JumpFactor

	!Fluorescent-lines cross sections
        PURE FUNCTION CS_FluorLine(Z,line,E) BIND(C,NAME='CS_FluorLine')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_FluorLine
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z,line
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E
        END FUNCTION CS_FluorLine

        PURE FUNCTION CSb_FluorLine(Z,line,E) &
		BIND(C,NAME='CSb_FluorLine')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_FluorLine
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z,line
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E
        END FUNCTION CSb_FluorLine

	!Fractional radiative rate	
	PURE FUNCTION RadRate(Z, line) BIND (C,NAME='RadRate')
                USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: RadRate
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: Z , line
	ENDFUNCTION RadRate

	!Photon energy after Compton scattering
	PURE FUNCTION ComptonEnergy(E0 , theta) BIND(C,NAME='ComptonEnergy')
                USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: ComptonEnergy
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E0 , theta
	ENDFUNCTION ComptonEnergy

	!Anomalous Scattering Factors
	PURE FUNCTION Fi (Z , E) BIND(C, NAME='Fi')
                USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: Fi
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION Fi

	PURE FUNCTION Fii (Z , E) BIND(C, NAME='Fii')
                USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: Fii
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION Fii

	!Kissel photoelectric cross sections
	PURE FUNCTION CS_Photo_Total (Z, E) BIND(C, NAME='CS_Photo_Total')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CS_Photo_Total
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION CS_Photo_Total

	PURE FUNCTION CSb_Photo_Total (Z, E) BIND(C, NAME='CSb_Photo_Total')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CSb_Photo_Total
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION CSb_Photo_Total

	PURE FUNCTION CS_Photo_Partial (Z,shell, E) &
		BIND(C, NAME='CS_Photo_Partial')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CS_Photo_Partial
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: shell, Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
	ENDFUNCTION CS_Photo_Partial

	PURE FUNCTION CSb_Photo_Partial (Z,shell, E) &
		BIND(C, NAME='CSb_Photo_Partial')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CSb_Photo_Partial
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: Z, shell
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
	ENDFUNCTION CSb_Photo_Partial

	!XRF cross sections using Kissel partial photoelectric cross sections
	PURE FUNCTION CS_FluorLine_Kissel (Z,line, E) &
		BIND(C, NAME='CS_FluorLine_Kissel')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CS_FluorLine_Kissel
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: line, Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
	ENDFUNCTION CS_FluorLine_Kissel

	PURE FUNCTION CSb_FluorLine_Kissel (Z,line, E) & 
		BIND(C, NAME='CSb_FluorLine_Kissel')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CSb_FluorLine_Kissel
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: line, Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
	ENDFUNCTION CSb_FluorLine_Kissel

	PURE FUNCTION CS_Total_Kissel (Z, E) BIND(C, NAME='CS_Total_Kissel')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CS_Total_Kissel
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION CS_Total_Kissel

	PURE FUNCTION CSb_Total_Kissel (Z, E) BIND(C, NAME='CSb_Total_Kissel')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CSb_Total_Kissel
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION CSb_Total_Kissel

        FUNCTION CompoundParser(compoundString, cd) BIND(C,NAME='CompoundParser')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPORT :: compoundData_C
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compoundString
                TYPE(compoundData_C),INTENT(INOUT) :: cd
                INTEGER (KIND=C_INT) :: CompoundParser
        ENDFUNCTION
        !compound parser based functions                
        PURE FUNCTION CS_Total_CP(compound,E) BIND(C,NAME='CS_Total_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Total_CP
        ENDFUNCTION CS_Total_CP

        PURE FUNCTION CS_Photo_CP(compound,E) BIND(C,NAME='CS_Photo_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Photo_CP
        ENDFUNCTION CS_Photo_CP

        PURE FUNCTION CS_Rayl_CP(compound,E) BIND(C,NAME='CS_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Rayl_CP
        ENDFUNCTION CS_Rayl_CP

        PURE FUNCTION CS_Compt_CP(compound,E) BIND(C,NAME='CS_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Compt_CP
        ENDFUNCTION CS_Compt_CP

        PURE FUNCTION CSb_Total_CP(compound,E) BIND(C,NAME='CSb_Total_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Total_CP
        ENDFUNCTION CSb_Total_CP

        PURE FUNCTION CSb_Photo_CP(compound,E) BIND(C,NAME='CSb_Photo_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Photo_CP
        ENDFUNCTION CSb_Photo_CP

        PURE FUNCTION CSb_Rayl_CP(compound,E) BIND(C,NAME='CSb_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Rayl_CP
        ENDFUNCTION CSb_Rayl_CP

        PURE FUNCTION CSb_Compt_CP(compound,E) BIND(C,NAME='CSb_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Compt_CP
        ENDFUNCTION CSb_Compt_CP

        PURE FUNCTION DCS_Rayl_CP(compound,E,theta) BIND(C,NAME='DCS_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta
                REAL (KIND=C_FLOAT) :: DCS_Rayl_CP
        ENDFUNCTION DCS_Rayl_CP

        PURE FUNCTION DCS_Compt_CP(compound,E,theta) BIND(C,NAME='DCS_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta
                REAL (KIND=C_FLOAT) :: DCS_Compt_CP
        ENDFUNCTION DCS_Compt_CP

        PURE FUNCTION DCSb_Rayl_CP(compound,E,theta) BIND(C,NAME='DCSb_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta
                REAL (KIND=C_FLOAT) :: DCSb_Rayl_CP
        ENDFUNCTION DCSb_Rayl_CP

        PURE FUNCTION DCSb_Compt_CP(compound,E,theta) BIND(C,NAME='DCSb_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta
                REAL (KIND=C_FLOAT) :: DCSb_Compt_CP
        ENDFUNCTION DCSb_Compt_CP

        PURE FUNCTION DCSP_Rayl_CP(compound,E,theta,phi) BIND(C,NAME='DCSP_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta,phi
                REAL (KIND=C_FLOAT) :: DCSP_Rayl_CP
        ENDFUNCTION DCSP_Rayl_CP

        PURE FUNCTION DCSP_Compt_CP(compound,E,theta,phi) BIND(C,NAME='DCSP_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta,phi
                REAL (KIND=C_FLOAT) :: DCSP_Compt_CP
        ENDFUNCTION DCSP_Compt_CP

        PURE FUNCTION DCSPb_Rayl_CP(compound,E,theta,phi) BIND(C,NAME='DCSPb_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta,phi
                REAL (KIND=C_FLOAT) :: DCSPb_Rayl_CP
        ENDFUNCTION DCSPb_Rayl_CP

        PURE FUNCTION DCSPb_Compt_CP(compound,E,theta,phi) BIND(C,NAME='DCSPb_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta,phi
                REAL (KIND=C_FLOAT) :: DCSPb_Compt_CP
        ENDFUNCTION DCSPb_Compt_CP

        PURE FUNCTION CS_Photo_Total_CP(compound,E) BIND(C,NAME='CS_Photo_Total_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Photo_Total_CP
        ENDFUNCTION CS_Photo_Total_CP

        PURE FUNCTION CSb_Photo_Total_CP(compound,E) BIND(C,NAME='CSb_Photo_Total_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Photo_Total_CP
        ENDFUNCTION CSb_Photo_Total_CP

        PURE FUNCTION CS_Total_Kissel_CP(compound,E) BIND(C,NAME='CS_Total_Kissel_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Total_Kissel_CP
        ENDFUNCTION CS_Total_Kissel_CP

        PURE FUNCTION CSb_Total_Kissel_CP(compound,E) BIND(C,NAME='CSb_Total_Kissel_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Total_Kissel_CP
        ENDFUNCTION CSb_Total_Kissel_CP

        PURE FUNCTION Refractive_Index_Re(compound,E,density) BIND(C,NAME='Refractive_Index_Re')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E, density
                REAL (KIND=C_FLOAT) :: Refractive_Index_Re
        ENDFUNCTION Refractive_Index_Re

        PURE FUNCTION Refractive_Index_Im(compound,E,density) BIND(C,NAME='Refractive_Index_Im')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E, density
                REAL (KIND=C_FLOAT) :: Refractive_Index_Im
        ENDFUNCTION Refractive_Index_Im

ENDINTERFACE

CONTAINS
!subroutine to associate a C structure with the correspond Fortran structure
SUBROUTINE compoundDataAssoc(in_C, out_F)
        USE, INTRINSIC :: ISO_C_BINDING
        IMPLICIT NONE
        TYPE(compoundData_C),INTENT(IN) :: in_C
        TYPE(compoundData_F),INTENT(INOUT) :: out_F

        out_F%nElements = in_C%nElements
        out_F%nAtomsAll = in_C%nAtomsAll
        CALL C_F_POINTER(in_C%Elements,out_F%Elements,[out_F%nElements])
        CALL C_F_POINTER(in_C%massFractions,out_F%massFractions,[out_F%nElements])

ENDSUBROUTINE compoundDataAssoc

ENDMODULE
