
!Copyright (c) 2009, Tom Schoonjans
!All rights reserved.

!Redistribution and use in source and binary forms, with or without
!modification, are permitted provided that the following conditions are met:
!    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
!    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
!    * The names of the contributors may not be used to endorse or promote products derived from this software without specific prior written permission.

!THIS SOFTWARE IS PROVIDED BY Tom Schoonjans ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Tom Schoonjans BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



!Fortran 2003 bindings for xraylib
!By Tom Schoonjans (Tom.Schoonjans@UGent.be)

!Warning: can ony be compiled with Intel Fortran 10 or later, GFortran 4.3.0 or later and G95




      


MODULE xraylib

USE, INTRINSIC :: ISO_C_BINDING
IMPLICIT NONE

TYPE, BIND(C) :: compoundData_C
        INTEGER (C_INT) :: nElements
        INTEGER (C_INT) :: nAtomsAll
        TYPE (C_PTR) :: Elements
        TYPE (C_PTR) :: massFractions
ENDTYPE 

TYPE :: compoundData_F
        INTEGER (C_INT) :: nElements
        INTEGER (C_INT) :: nAtomsAll
        INTEGER (C_INT),DIMENSION(:),POINTER :: Elements
        REAL (C_DOUBLE),DIMENSION(:),POINTER :: massFractions
ENDTYPE 


!Constants


INTEGER (KIND=C_INT),PARAMETER ::  F1_TRANS   = 0
INTEGER (KIND=C_INT),PARAMETER ::  F12_TRANS  = 1
INTEGER (KIND=C_INT),PARAMETER ::  F13_TRANS  = 2
INTEGER (KIND=C_INT),PARAMETER ::  FP13_TRANS = 3
INTEGER (KIND=C_INT),PARAMETER ::  F23_TRANS  = 4

INTEGER (KIND=C_INT),PARAMETER ::  KA_LINE = 0
INTEGER (KIND=C_INT),PARAMETER ::  KB_LINE = 1
INTEGER (KIND=C_INT),PARAMETER ::  LA_LINE = 2
INTEGER (KIND=C_INT),PARAMETER ::  LB_LINE = 3
INTEGER (KIND=C_INT),PARAMETER ::  KL1_LINE = -1
INTEGER (KIND=C_INT),PARAMETER ::  KL2_LINE = -2
INTEGER (KIND=C_INT),PARAMETER ::  KL3_LINE = -3
INTEGER (KIND=C_INT),PARAMETER ::  KM1_LINE = -4
INTEGER (KIND=C_INT),PARAMETER ::  KM2_LINE = -5
INTEGER (KIND=C_INT),PARAMETER ::  KM3_LINE = -6
INTEGER (KIND=C_INT),PARAMETER ::  KM4_LINE = -7
INTEGER (KIND=C_INT),PARAMETER ::  KM5_LINE = -8
INTEGER (KIND=C_INT),PARAMETER ::  KN1_LINE = -9
INTEGER (KIND=C_INT),PARAMETER ::  KN2_LINE = -10
INTEGER (KIND=C_INT),PARAMETER ::  KN3_LINE = -11
INTEGER (KIND=C_INT),PARAMETER ::  KN4_LINE = -12
INTEGER (KIND=C_INT),PARAMETER ::  KN5_LINE = -13
INTEGER (KIND=C_INT),PARAMETER ::  L1M1_LINE = -14
INTEGER (KIND=C_INT),PARAMETER ::  L1M2_LINE = -15
INTEGER (KIND=C_INT),PARAMETER ::  L1M3_LINE = -16
INTEGER (KIND=C_INT),PARAMETER ::  L1M4_LINE = -17
INTEGER (KIND=C_INT),PARAMETER ::  L1M5_LINE = -18
INTEGER (KIND=C_INT),PARAMETER ::  L1N1_LINE = -19
INTEGER (KIND=C_INT),PARAMETER ::  L1N2_LINE = -20
INTEGER (KIND=C_INT),PARAMETER ::  L1N3_LINE = -21
INTEGER (KIND=C_INT),PARAMETER ::  L1N4_LINE = -22
INTEGER (KIND=C_INT),PARAMETER ::  L1N5_LINE = -23
INTEGER (KIND=C_INT),PARAMETER ::  L1N6_LINE = -24
INTEGER (KIND=C_INT),PARAMETER ::  L1N7_LINE = -25
INTEGER (KIND=C_INT),PARAMETER ::  L2M1_LINE = -26
INTEGER (KIND=C_INT),PARAMETER ::  L2M2_LINE = -27
INTEGER (KIND=C_INT),PARAMETER ::  L2M3_LINE = -28
INTEGER (KIND=C_INT),PARAMETER ::  L2M4_LINE = -29
INTEGER (KIND=C_INT),PARAMETER ::  L2M5_LINE = -30
INTEGER (KIND=C_INT),PARAMETER ::  L2N1_LINE = -31
INTEGER (KIND=C_INT),PARAMETER ::  L2N2_LINE = -32
INTEGER (KIND=C_INT),PARAMETER ::  L2N3_LINE = -33
INTEGER (KIND=C_INT),PARAMETER ::  L2N4_LINE = -34
INTEGER (KIND=C_INT),PARAMETER ::  L2N5_LINE = -35
INTEGER (KIND=C_INT),PARAMETER ::  L2N6_LINE = -36
INTEGER (KIND=C_INT),PARAMETER ::  L2N7_LINE = -37
INTEGER (KIND=C_INT),PARAMETER ::  L3M1_LINE = -38
INTEGER (KIND=C_INT),PARAMETER ::  L3M2_LINE = -39
INTEGER (KIND=C_INT),PARAMETER ::  L3M3_LINE = -40
INTEGER (KIND=C_INT),PARAMETER ::  L3M4_LINE = -41
INTEGER (KIND=C_INT),PARAMETER ::  L3M5_LINE = -42
INTEGER (KIND=C_INT),PARAMETER ::  L3N1_LINE = -43
INTEGER (KIND=C_INT),PARAMETER ::  L3N2_LINE = -44
INTEGER (KIND=C_INT),PARAMETER ::  L3N3_LINE = -45
INTEGER (KIND=C_INT),PARAMETER ::  L3N4_LINE = -46
INTEGER (KIND=C_INT),PARAMETER ::  L3N5_LINE = -47
INTEGER (KIND=C_INT),PARAMETER ::  L3N6_LINE = -48
INTEGER (KIND=C_INT),PARAMETER ::  L3N7_LINE = -49
INTEGER (KIND=C_INT),PARAMETER :: KN45_LINE = -50
INTEGER (KIND=C_INT),PARAMETER :: KO23_LINE = -51
INTEGER (KIND=C_INT),PARAMETER :: KO45_LINE = -52
INTEGER (KIND=C_INT),PARAMETER :: KP23_LINE = -53
INTEGER (KIND=C_INT),PARAMETER :: L1L3_LINE = -54
INTEGER (KIND=C_INT),PARAMETER :: L1M45_LINE = -55
INTEGER (KIND=C_INT),PARAMETER :: L1N45_LINE = -56
INTEGER (KIND=C_INT),PARAMETER :: L1O23_LINE = -57
INTEGER (KIND=C_INT),PARAMETER :: L1P23_LINE = -58
INTEGER (KIND=C_INT),PARAMETER :: L2O1_LINE = -59
INTEGER (KIND=C_INT),PARAMETER :: L2O4_LINE = -60
INTEGER (KIND=C_INT),PARAMETER :: L2P1_LINE = -61
INTEGER (KIND=C_INT),PARAMETER :: L3O1_LINE = -62
INTEGER (KIND=C_INT),PARAMETER :: L3O45_LINE = -63
INTEGER (KIND=C_INT),PARAMETER :: L3P1_LINE = -64
INTEGER (KIND=C_INT),PARAMETER :: M1M2_LINE = -65
INTEGER (KIND=C_INT),PARAMETER :: M1M3_LINE = -66
INTEGER (KIND=C_INT),PARAMETER :: M1M4_LINE = -67
INTEGER (KIND=C_INT),PARAMETER :: M1M5_LINE = -68
INTEGER (KIND=C_INT),PARAMETER :: M1N1_LINE = -69
INTEGER (KIND=C_INT),PARAMETER :: M1N2_LINE = -70
INTEGER (KIND=C_INT),PARAMETER :: M1N3_LINE = -71
INTEGER (KIND=C_INT),PARAMETER :: M1N4_LINE = -72
INTEGER (KIND=C_INT),PARAMETER :: M1N5_LINE = -73
INTEGER (KIND=C_INT),PARAMETER :: M1N6_LINE = -74
INTEGER (KIND=C_INT),PARAMETER :: M1N7_LINE = -75
INTEGER (KIND=C_INT),PARAMETER :: M1O1_LINE = -76
INTEGER (KIND=C_INT),PARAMETER :: M1O2_LINE = -77
INTEGER (KIND=C_INT),PARAMETER :: M1O3_LINE = -78
INTEGER (KIND=C_INT),PARAMETER :: M1O4_LINE = -79
INTEGER (KIND=C_INT),PARAMETER :: M1O5_LINE = -80
INTEGER (KIND=C_INT),PARAMETER :: M1P2_LINE = -81
INTEGER (KIND=C_INT),PARAMETER :: M1P3_LINE = -82
INTEGER (KIND=C_INT),PARAMETER :: M2M3_LINE = -83
INTEGER (KIND=C_INT),PARAMETER :: M2M4_LINE = -84
INTEGER (KIND=C_INT),PARAMETER :: M2M5_LINE = -85
INTEGER (KIND=C_INT),PARAMETER :: M2N1_LINE = -86
INTEGER (KIND=C_INT),PARAMETER :: M2N2_LINE = -87
INTEGER (KIND=C_INT),PARAMETER :: M2N3_LINE = -88
INTEGER (KIND=C_INT),PARAMETER :: M2N4_LINE = -89
INTEGER (KIND=C_INT),PARAMETER :: M2N5_LINE = -90
INTEGER (KIND=C_INT),PARAMETER :: M2N6_LINE = -91
INTEGER (KIND=C_INT),PARAMETER :: M2N7_LINE = -92
INTEGER (KIND=C_INT),PARAMETER :: M2O1_LINE = -93
INTEGER (KIND=C_INT),PARAMETER :: M2O2_LINE = -94
INTEGER (KIND=C_INT),PARAMETER :: M2O3_LINE = -95
INTEGER (KIND=C_INT),PARAMETER :: M2O4_LINE = -96
INTEGER (KIND=C_INT),PARAMETER :: M2O5_LINE = -97
INTEGER (KIND=C_INT),PARAMETER :: M2O6_LINE = -98
INTEGER (KIND=C_INT),PARAMETER :: M2P1_LINE = -99
INTEGER (KIND=C_INT),PARAMETER :: M2P4_LINE = -100
INTEGER (KIND=C_INT),PARAMETER :: M3M4_LINE = -101
INTEGER (KIND=C_INT),PARAMETER :: M3M5_LINE = -102
INTEGER (KIND=C_INT),PARAMETER :: M3N1_LINE = -103
INTEGER (KIND=C_INT),PARAMETER :: M3N2_LINE = -104
INTEGER (KIND=C_INT),PARAMETER :: M3N3_LINE = -105
INTEGER (KIND=C_INT),PARAMETER :: M3N4_LINE = -106
INTEGER (KIND=C_INT),PARAMETER :: M3N5_LINE = -107
INTEGER (KIND=C_INT),PARAMETER :: M3N6_LINE = -108
INTEGER (KIND=C_INT),PARAMETER :: M3N7_LINE = -109
INTEGER (KIND=C_INT),PARAMETER :: M3O1_LINE = -110
INTEGER (KIND=C_INT),PARAMETER :: M3O2_LINE = -111
INTEGER (KIND=C_INT),PARAMETER :: M3O3_LINE = -112
INTEGER (KIND=C_INT),PARAMETER :: M3O4_LINE = -113
INTEGER (KIND=C_INT),PARAMETER :: M3O5_LINE = -114
INTEGER (KIND=C_INT),PARAMETER :: M3O6_LINE = -115
INTEGER (KIND=C_INT),PARAMETER :: M3P2_LINE = -116
INTEGER (KIND=C_INT),PARAMETER :: M3Q1_LINE = -117
INTEGER (KIND=C_INT),PARAMETER :: M4M5_LINE = -118
INTEGER (KIND=C_INT),PARAMETER :: M4N1_LINE = -119
INTEGER (KIND=C_INT),PARAMETER :: M4N2_LINE = -120
INTEGER (KIND=C_INT),PARAMETER :: M4N3_LINE = -121
INTEGER (KIND=C_INT),PARAMETER :: M4N4_LINE = -122
INTEGER (KIND=C_INT),PARAMETER :: M4N5_LINE = -123
INTEGER (KIND=C_INT),PARAMETER :: M4N6_LINE = -124
INTEGER (KIND=C_INT),PARAMETER :: M4N7_LINE = -125
INTEGER (KIND=C_INT),PARAMETER :: M4O1_LINE = -126
INTEGER (KIND=C_INT),PARAMETER :: M4O2_LINE = -127
INTEGER (KIND=C_INT),PARAMETER :: M4O3_LINE = -128
INTEGER (KIND=C_INT),PARAMETER :: M4O4_LINE = -129
INTEGER (KIND=C_INT),PARAMETER :: M4O5_LINE = -130
INTEGER (KIND=C_INT),PARAMETER :: M4O6_LINE = -131
INTEGER (KIND=C_INT),PARAMETER :: M4P1_LINE = -132
INTEGER (KIND=C_INT),PARAMETER :: M4P2_LINE = -133
INTEGER (KIND=C_INT),PARAMETER :: M4P3_LINE = -134
INTEGER (KIND=C_INT),PARAMETER :: M5N1_LINE = -135
INTEGER (KIND=C_INT),PARAMETER :: M5N2_LINE = -136
INTEGER (KIND=C_INT),PARAMETER :: M5N3_LINE = -137
INTEGER (KIND=C_INT),PARAMETER :: M5N4_LINE = -138
INTEGER (KIND=C_INT),PARAMETER :: M5N5_LINE = -139
INTEGER (KIND=C_INT),PARAMETER :: M5N6_LINE = -140
INTEGER (KIND=C_INT),PARAMETER :: M5N7_LINE = -141
INTEGER (KIND=C_INT),PARAMETER :: M5O1_LINE = -142
INTEGER (KIND=C_INT),PARAMETER :: M5O2_LINE = -143
INTEGER (KIND=C_INT),PARAMETER :: M5O3_LINE = -144
INTEGER (KIND=C_INT),PARAMETER :: M5O4_LINE = -145
INTEGER (KIND=C_INT),PARAMETER :: M5O5_LINE = -146
INTEGER (KIND=C_INT),PARAMETER :: M5O6_LINE = -147
INTEGER (KIND=C_INT),PARAMETER :: M5P1_LINE = -148
INTEGER (KIND=C_INT),PARAMETER :: M5P3_LINE = -149
INTEGER (KIND=C_INT),PARAMETER :: M5P4_LINE = -150

INTEGER (KIND=C_INT),PARAMETER ::  K_SHELL = 0
INTEGER (KIND=C_INT),PARAMETER ::  L1_SHELL = 1
INTEGER (KIND=C_INT),PARAMETER ::  L2_SHELL = 2
INTEGER (KIND=C_INT),PARAMETER ::  L3_SHELL = 3
INTEGER (KIND=C_INT),PARAMETER ::  M1_SHELL = 4
INTEGER (KIND=C_INT),PARAMETER ::  M2_SHELL = 5
INTEGER (KIND=C_INT),PARAMETER ::  M3_SHELL = 6
INTEGER (KIND=C_INT),PARAMETER ::  M4_SHELL = 7
INTEGER (KIND=C_INT),PARAMETER ::  M5_SHELL = 8
INTEGER (KIND=C_INT),PARAMETER ::  N1_SHELL = 9
INTEGER (KIND=C_INT),PARAMETER ::  N2_SHELL = 10
INTEGER (KIND=C_INT),PARAMETER ::  N3_SHELL = 11
INTEGER (KIND=C_INT),PARAMETER ::  N4_SHELL = 12
INTEGER (KIND=C_INT),PARAMETER ::  N5_SHELL = 13
INTEGER (KIND=C_INT),PARAMETER ::  N6_SHELL = 14
INTEGER (KIND=C_INT),PARAMETER ::  N7_SHELL = 15
INTEGER (KIND=C_INT),PARAMETER ::  O1_SHELL = 16
INTEGER (KIND=C_INT),PARAMETER ::  O2_SHELL = 17
INTEGER (KIND=C_INT),PARAMETER ::  O3_SHELL = 18
INTEGER (KIND=C_INT),PARAMETER ::  O4_SHELL = 19
INTEGER (KIND=C_INT),PARAMETER ::  O5_SHELL = 20
INTEGER (KIND=C_INT),PARAMETER ::  O6_SHELL = 21
INTEGER (KIND=C_INT),PARAMETER ::  O7_SHELL = 22
INTEGER (KIND=C_INT),PARAMETER ::  P1_SHELL = 23
INTEGER (KIND=C_INT),PARAMETER ::  P2_SHELL = 24
INTEGER (KIND=C_INT),PARAMETER ::  P3_SHELL = 25
INTEGER (KIND=C_INT),PARAMETER ::  P4_SHELL = 26
INTEGER (KIND=C_INT),PARAMETER ::  P5_SHELL = 27
INTEGER (KIND=C_INT),PARAMETER ::  Q1_SHELL = 28
INTEGER (KIND=C_INT),PARAMETER ::  Q2_SHELL = 29
INTEGER (KIND=C_INT),PARAMETER ::  Q3_SHELL = 30




INTERFACE
!All procedures are pure

	!Initialization
	SUBROUTINE XRayInit() BIND(C,NAME='XRayInit')
	ENDSUBROUTINE XRayInit

	!Error handling
	PURE SUBROUTINE SetHardExit(hard_exit) BIND(C,NAME='SetHardExit')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
		INTEGER (KIND=C_INT),INTENT(IN),VALUE :: hard_exit
	ENDSUBROUTINE SetHardExit

	PURE SUBROUTINE SetExitStatus(exit_status) BIND(C,NAME='SetExitStatus')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
		INTEGER (KIND=C_INT),INTENT(IN),VALUE :: exit_status
	ENDSUBROUTINE SetExitStatus

	PURE FUNCTION GetExitStatus() BIND(C,NAME='GetExitStatus')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
		INTEGER (KIND=C_INT) :: GetExitStatus
	ENDFUNCTION

	!Atomic Weights
        PURE FUNCTION AtomicWeight(Z) BIND(C,NAME='AtomicWeight')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: AtomicWeight
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
        END FUNCTION AtomicWeight

	!Cross sections (cm2/g)
        PURE FUNCTION CS_Total(Z,E) BIND(C,NAME='CS_Total')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_Total
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E
        END FUNCTION CS_Total

        PURE FUNCTION CS_Photo(Z,E) BIND(C,NAME='CS_Photo')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_Photo
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CS_Photo

        PURE FUNCTION CS_Rayl(Z,E) BIND(C,NAME='CS_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_Rayl
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CS_Rayl

        PURE FUNCTION CS_Compt(Z,E) BIND(C,NAME='CS_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_Compt
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CS_Compt

        PURE FUNCTION CS_KN(E) BIND(C,NAME='CS_KN')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_KN
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CS_KN

	!Cross sections (barn/atom)
        PURE FUNCTION CSb_Total(Z,E) BIND(C,NAME='CSb_Total')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_Total
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E
        END FUNCTION CSb_Total

        PURE FUNCTION CSb_Photo(Z,E) BIND(C,NAME='CSb_Photo')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_Photo
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CSb_Photo

        PURE FUNCTION CSb_Rayl(Z,E) BIND(C,NAME='CSb_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_Rayl
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CSb_Rayl

        PURE FUNCTION CSb_Compt(Z,E) BIND(C,NAME='CSb_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_Compt
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z
                REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: E
        END FUNCTION CSb_Compt

	!Unpolarized differential scattering cross sections
	PURE FUNCTION DCS_Thoms(theta) BIND(C,NAME='DCS_Thoms')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCS_Thoms
		REAL (KIND=C_FLOAT),INTENT(IN),VALUE :: theta
	ENDFUNCTION DCS_Thoms

	PURE FUNCTION DCS_KN(E ,theta) BIND(C,NAME='DCS_KN')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCS_KN
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E, theta
	ENDFUNCTION DCS_KN

	PURE FUNCTION DCS_Rayl(Z ,E ,theta) BIND(C,NAME='DCS_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCS_Rayl
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E,theta
	ENDFUNCTION DCS_Rayl

	PURE FUNCTION DCS_Compt(Z ,E ,theta) BIND(C,NAME='DCS_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCS_Compt
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E,theta
	ENDFUNCTION DCS_Compt

	PURE FUNCTION DCSb_Rayl(Z ,E ,theta) BIND(C,NAME='DCSb_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSb_Rayl
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E,theta
	ENDFUNCTION DCSb_Rayl

	PURE FUNCTION DCSb_Compt(Z ,E ,theta) BIND(C,NAME='DCSb_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSb_Compt
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E,theta
	ENDFUNCTION DCSb_Compt

	!Polarized differential scattering cross sections
	PURE FUNCTION DCSP_Thoms(theta, phi) BIND(C,NAME='DCSP_Thoms')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSP_Thoms
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: theta, phi
	ENDFUNCTION DCSP_Thoms

	PURE FUNCTION DCSP_KN(E, theta, phi) BIND(C,NAME='DCSP_KN')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSP_KN
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSP_KN

	PURE FUNCTION DCSP_Rayl(Z, E, theta, phi) BIND(C,NAME='DCSP_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSP_Rayl
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSP_Rayl

	PURE FUNCTION DCSP_Compt(Z, E, theta, phi) BIND(C,NAME='DCSP_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSP_Compt
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSP_Compt

	PURE FUNCTION DCSPb_Rayl(Z, E, theta, phi) BIND(C,NAME='DCSPb_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSPb_Rayl
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSPb_Rayl

	PURE FUNCTION DCSPb_Compt(Z, E, theta, phi) BIND(C,NAME='DCSPb_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: DCSPb_Compt
		INTEGER (KIND=C_INT), INTENT(IN),VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E, theta, phi
	ENDFUNCTION DCSPb_Compt
	
	!Scattering factors
	PURE FUNCTION FF_Rayl(Z , q) BIND(C,NAME='FF_Rayl')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: FF_Rayl
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: q
	ENDFUNCTION FF_Rayl

	PURE FUNCTION SF_Compt(Z , q) BIND(C,NAME='SF_Compt')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: SF_Compt
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: q
	ENDFUNCTION SF_Compt

	PURE FUNCTION MomentTransf(E , theta) BIND(C,NAME='MomentTransf')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: MomentTransf
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E , theta
	ENDFUNCTION

	!X-ray fluorescent line energy
        PURE FUNCTION LineEnergy(Z,line) BIND(C,NAME='LineEnergy')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: LineEnergy
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z,line
        END FUNCTION LineEnergy

	!Fluorescence yield
        PURE FUNCTION FluorYield(Z,shell) BIND(C,NAME='FluorYield')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: FluorYield
                INTEGER (KIND=C_INT),INTENT(IN),VALUE ::Z,shell
        END FUNCTION FluorYield

	!Coster-Kronig transition probability
        PURE FUNCTION CosKronTransProb(Z,trans) &
		BIND(C,NAME='CosKronTransProb')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CosKronTransProb
                INTEGER (KIND=C_INT),INTENT(IN),VALUE ::Z,trans
        END FUNCTION CosKronTransProb

	!Absorption-edge energies
        PURE FUNCTION EdgeEnergy(Z,shell) BIND(C,NAME='EdgeEnergy')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: EdgeEnergy
                INTEGER (KIND=C_INT),INTENT(IN),VALUE ::Z,shell
        END FUNCTION EdgeEnergy

	!Jump ratios
        PURE FUNCTION JumpFactor(Z,shell) BIND(C,NAME='JumpFactor')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: JumpFactor
                INTEGER (KIND=C_INT),INTENT(IN),VALUE ::Z,shell
        END FUNCTION JumpFactor

	!Fluorescent-lines cross sections
        PURE FUNCTION CS_FluorLine(Z,line,E) BIND(C,NAME='CS_FluorLine')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CS_FluorLine
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z,line
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E
        END FUNCTION CS_FluorLine

        PURE FUNCTION CSb_FluorLine(Z,line,E) &
		BIND(C,NAME='CSb_FluorLine')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                REAL (KIND=C_FLOAT) :: CSb_FluorLine
                INTEGER (KIND=C_INT),INTENT(IN),VALUE :: Z,line
		REAL (KIND=C_FLOAT), INTENT(IN),VALUE :: E
        END FUNCTION CSb_FluorLine

	!Fractional radiative rate	
	PURE FUNCTION RadRate(Z, line) BIND (C,NAME='RadRate')
                USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: RadRate
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: Z , line
	ENDFUNCTION RadRate

	!Photon energy after Compton scattering
	PURE FUNCTION ComptonEnergy(E0 , theta) BIND(C,NAME='ComptonEnergy')
                USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: ComptonEnergy
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E0 , theta
	ENDFUNCTION ComptonEnergy

	!Anomalous Scattering Factors
	PURE FUNCTION Fi (Z , E) BIND(C, NAME='Fi')
                USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: Fi
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION Fi

	PURE FUNCTION Fii (Z , E) BIND(C, NAME='Fii')
                USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: Fii
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION Fii

	!Kissel photoelectric cross sections
	PURE FUNCTION CS_Photo_Total (Z, E) BIND(C, NAME='CS_Photo_Total')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CS_Photo_Total
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION CS_Photo_Total

	PURE FUNCTION CSb_Photo_Total (Z, E) BIND(C, NAME='CSb_Photo_Total')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CSb_Photo_Total
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION CSb_Photo_Total

	PURE FUNCTION CS_Photo_Partial (Z,shell, E) &
		BIND(C, NAME='CS_Photo_Partial')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CS_Photo_Partial
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: shell, Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
	ENDFUNCTION CS_Photo_Partial

	PURE FUNCTION CSb_Photo_Partial (Z,shell, E) &
		BIND(C, NAME='CSb_Photo_Partial')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CSb_Photo_Partial
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: Z, shell
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
	ENDFUNCTION CSb_Photo_Partial

	!XRF cross sections using Kissel partial photoelectric cross sections
	PURE FUNCTION CS_FluorLine_Kissel (Z,line, E) &
		BIND(C, NAME='CS_FluorLine_Kissel')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CS_FluorLine_Kissel
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: line, Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
	ENDFUNCTION CS_FluorLine_Kissel

	PURE FUNCTION CSb_FluorLine_Kissel (Z,line, E) & 
		BIND(C, NAME='CSb_FluorLine_Kissel')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CSb_FluorLine_Kissel
		INTEGER (KIND=C_INT), INTENT(IN), VALUE :: line, Z
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
	ENDFUNCTION CSb_FluorLine_Kissel

	PURE FUNCTION CS_Total_Kissel (Z, E) BIND(C, NAME='CS_Total_Kissel')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CS_Total_Kissel
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION CS_Total_Kissel

	PURE FUNCTION CSb_Total_Kissel (Z, E) BIND(C, NAME='CSb_Total_Kissel')
		USE, INTRINSIC :: ISO_C_BINDING
		IMPLICIT NONE
		REAL (KIND=C_FLOAT) :: CSb_Total_Kissel
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
		INTEGER (KIND=C_INT),INTENT(IN), VALUE :: Z 
	ENDFUNCTION CSb_Total_Kissel

        FUNCTION CompoundParser(compoundString, cd) BIND(C,NAME='CompoundParser')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPORT :: compoundData_C
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compoundString
                TYPE(compoundData_C),INTENT(INOUT) :: cd
                INTEGER (KIND=C_INT) :: CompoundParser
        ENDFUNCTION
        !compound parser based functions                
        PURE FUNCTION CS_Total_CP(compound,E) BIND(C,NAME='CS_Total_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Total_CP
        ENDFUNCTION CS_Total_CP

        PURE FUNCTION CS_Photo_CP(compound,E) BIND(C,NAME='CS_Photo_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Photo_CP
        ENDFUNCTION CS_Photo_CP

        PURE FUNCTION CS_Rayl_CP(compound,E) BIND(C,NAME='CS_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Rayl_CP
        ENDFUNCTION CS_Rayl_CP

        PURE FUNCTION CS_Compt_CP(compound,E) BIND(C,NAME='CS_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Compt_CP
        ENDFUNCTION CS_Compt_CP

        PURE FUNCTION CSb_Total_CP(compound,E) BIND(C,NAME='CSb_Total_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Total_CP
        ENDFUNCTION CSb_Total_CP

        PURE FUNCTION CSb_Photo_CP(compound,E) BIND(C,NAME='CSb_Photo_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Photo_CP
        ENDFUNCTION CSb_Photo_CP

        PURE FUNCTION CSb_Rayl_CP(compound,E) BIND(C,NAME='CSb_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Rayl_CP
        ENDFUNCTION CSb_Rayl_CP

        PURE FUNCTION CSb_Compt_CP(compound,E) BIND(C,NAME='CSb_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Compt_CP
        ENDFUNCTION CSb_Compt_CP

        PURE FUNCTION DCS_Rayl_CP(compound,E,theta) BIND(C,NAME='DCS_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta
                REAL (KIND=C_FLOAT) :: DCS_Rayl_CP
        ENDFUNCTION DCS_Rayl_CP

        PURE FUNCTION DCS_Compt_CP(compound,E,theta) BIND(C,NAME='DCS_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta
                REAL (KIND=C_FLOAT) :: DCS_Compt_CP
        ENDFUNCTION DCS_Compt_CP

        PURE FUNCTION DCSb_Rayl_CP(compound,E,theta) BIND(C,NAME='DCSb_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta
                REAL (KIND=C_FLOAT) :: DCSb_Rayl_CP
        ENDFUNCTION DCSb_Rayl_CP

        PURE FUNCTION DCSb_Compt_CP(compound,E,theta) BIND(C,NAME='DCSb_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta
                REAL (KIND=C_FLOAT) :: DCSb_Compt_CP
        ENDFUNCTION DCSb_Compt_CP

        PURE FUNCTION DCSP_Rayl_CP(compound,E,theta,phi) BIND(C,NAME='DCSP_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta,phi
                REAL (KIND=C_FLOAT) :: DCSP_Rayl_CP
        ENDFUNCTION DCSP_Rayl_CP

        PURE FUNCTION DCSP_Compt_CP(compound,E,theta,phi) BIND(C,NAME='DCSP_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta,phi
                REAL (KIND=C_FLOAT) :: DCSP_Compt_CP
        ENDFUNCTION DCSP_Compt_CP

        PURE FUNCTION DCSPb_Rayl_CP(compound,E,theta,phi) BIND(C,NAME='DCSPb_Rayl_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta,phi
                REAL (KIND=C_FLOAT) :: DCSPb_Rayl_CP
        ENDFUNCTION DCSPb_Rayl_CP

        PURE FUNCTION DCSPb_Compt_CP(compound,E,theta,phi) BIND(C,NAME='DCSPb_Compt_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E,theta,phi
                REAL (KIND=C_FLOAT) :: DCSPb_Compt_CP
        ENDFUNCTION DCSPb_Compt_CP

        PURE FUNCTION CS_Photo_Total_CP(compound,E) BIND(C,NAME='CS_Photo_Total_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Photo_Total_CP
        ENDFUNCTION CS_Photo_Total_CP

        PURE FUNCTION CSb_Photo_Total_CP(compound,E) BIND(C,NAME='CSb_Photo_Total_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Photo_Total_CP
        ENDFUNCTION CSb_Photo_Total_CP

        PURE FUNCTION CS_Total_Kissel_CP(compound,E) BIND(C,NAME='CS_Total_Kissel_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CS_Total_Kissel_CP
        ENDFUNCTION CS_Total_Kissel_CP

        PURE FUNCTION CSb_Total_Kissel_CP(compound,E) BIND(C,NAME='CSb_Total_Kissel_CP')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E
                REAL (KIND=C_FLOAT) :: CSb_Total_Kissel_CP
        ENDFUNCTION CSb_Total_Kissel_CP

        PURE FUNCTION Refractive_Index_Re(compound,E,density) BIND(C,NAME='Refractive_Index_Re')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E, density
                REAL (KIND=C_FLOAT) :: Refractive_Index_Re
        ENDFUNCTION Refractive_Index_Re

        PURE FUNCTION Refractive_Index_Im(compound,E,density) BIND(C,NAME='Refractive_Index_Im')
                USE, INTRINSIC :: ISO_C_BINDING
                IMPLICIT NONE
                CHARACTER (KIND=C_CHAR), DIMENSION(*),INTENT(IN) :: compound
		REAL (KIND=C_FLOAT), INTENT(IN), VALUE :: E, density
                REAL (KIND=C_FLOAT) :: Refractive_Index_Im
        ENDFUNCTION Refractive_Index_Im

ENDINTERFACE

CONTAINS
!subroutine to associate a C structure with the correspond Fortran structure
SUBROUTINE compoundDataAssoc(in_C, out_F)
        USE, INTRINSIC :: ISO_C_BINDING
        IMPLICIT NONE
        TYPE(compoundData_C),INTENT(IN) :: in_C
        TYPE(compoundData_F),INTENT(INOUT) :: out_F

        out_F%nElements = in_C%nElements
        out_F%nAtomsAll = in_C%nAtomsAll
        CALL C_F_POINTER(in_C%Elements,out_F%Elements,[out_F%nElements])
        CALL C_F_POINTER(in_C%massFractions,out_F%massFractions,[out_F%nElements])

ENDSUBROUTINE compoundDataAssoc

ENDMODULE
